### ISSUE TITLE
attempt to concatenate a nil value (upvalue 'safe_code')

### ISSUE THREAD

**Issue by gir489returns** [YimMenu-Lua/DailyCollectibles#26]
![image](https://github.com/user-attachments/assets/aa3fdf0d-eca8-42e3-aa90-67c50c29ceaa)

**Comment by ShinyWasabi** [comment]
Fixed by https://github.com/YimMenu-Lua/DailyCollectibles/commit/86c3419c681c9248391bebb6b23137b58fdd65c1
