### ISSUE TITLE
Complete All Daily Collectibles does not give GTA$ and RP

### ISSUE THREAD

**Issue by tokwa41** [YimMenu-Lua/DailyCollectibles#27]
The daily collectibles are shown as complete in the interaction menu however I do not get the GTA$ and RP for collecting them. Is this intended? And if so, would it be possible for Complete All Dailly Collectibles to also give GTA$ and RP?

**Comment by ShinyWasabi** [comment]
I found a way to achieve this by calling `func_7166` in `freemode`.
```cpp
static inline script_function set_collectable_collected("SCC", "freemode"_J, "2D 05 33 00 00", 0);

// Example Usage
enum eCollectableTypes : uint64_t
{
    COLLECTABLE_MOVIE_PROPS = 0,
    COLLECTABLE_HIDDEN_CACHES = 1,
    COLLECTABLE_TREASURE_CHESTS = 2,
    COLLECTABLE_RADIO_STATIONS = 3,
    COLLECTABLE_USB_PIRATE_RADIO = 4,
    COLLECTABLE_SHIPWRECKED = 5,
    COLLECTABLE_BURIED_STASH = 6,
    // COLLECTABLE_METAL_DETECTOR = 7, unused (turned into random event)
    COLLECTABLE_TRICK_OR_TREAT = 8,
    COLLECTABLE_LD_ORGANICS = 9,
    COLLECTABLE_SKYDIVES = 10,
    // COLLECTABLE_SIGHTSEEING = 11, unused (turned into random event)
    // COLLECTABLE_POLICE_BADGES = 12, unused (CnC)
    COLLECTABLE_GUN_PARTS = 13, // (crime scene random event, remnant from CnC)
    // 14-15 unknown/doesn't exist
    COLLECTABLE_SNOWMEN = 16,
    COLLECTABLE_DEAD_DROP = 17,
    // 18 unknown/doesn't exist
    COLLECTABLE_TAGGING = 19
};

// Args: collectable type, collectable location, set collected, display HUD message, some trick or treat thing
scr_functions::set_collectable_collected({COLLECTABLE_DEAD_DROP, 0, true, true, false});
```
Here's an example [video](https://i.imgur.com/HiUkKtv.mp4) (sorry for the quality). It works pretty good.

However, calling script functions isn't exposed to the Lua API yet. I will see if I can find a way to manipulate the script to call the function for me, or I will make a PR to expose script functions if possible.

**Comment by ShinyWasabi** [comment]
@tokwa41 I implemented the feature you requested: https://github.com/YimMenu-Lua/DailyCollectibles/commit/ff4f079075ed0bfc4569e883e893eb213601ea4e
There is a "collect" button next to the teleport button now. Make sure you have the latest YimMenu DLL.
