### ISSUE TITLE
[BUG]: Script Patch Causes Crash During Online Transition

### ISSUE THREAD

**Issue by xesdoog** [YimMenu-Lua/DailyCollectibles#28]
line [114](https://github.com/YimMenu-Lua/DailyCollectibles/blob/main/daily_collectibles.lua#L114) causes the game to crash during online transition from Single Player.

This is a log from before I quoted out both lines 114 and 118 (it's trimmed to the crash part because I was testing a few things which filled the console with information irrelevant to the issue):
[cout_1.txt](https://github.com/user-attachments/files/16703195/cout_1.txt)

This is after the lines were quoted out
[cout_2.txt](https://github.com/user-attachments/files/16703203/cout_2.txt)

Both messages `Failed to find pattern: Bypass Treasure Chest CP Check` and
`[FATAL/exception_handler.cpp:42] UNKNOWN_EXCEPTION: CODE: 3765269347` did not appear in the second log and the game finished its transition without crashing.

**Comment by ShinyWasabi** [comment]
Can you tell me the steps to reproduce this? It works for me.

**Comment by xesdoog** [comment]
> Can you tell me the steps to reproduce this? It works for me.

This is what I always do:
- Launch the game in Single Player.
- Inject YimMenu when SP fully loads.
- ALT-TAB and go back to VSC to test new features or fix old bugs of mine.
- If a feature is meant for online I'll start a new Invite-Only session and continue the cycle.

This was always my routine in GTA and I've had Daily Collectibles installed since you released it. Never had any crash issues but yesterday I was doing the same old thing and when I decided to go Online my game crashed. I checked the log and saw the `Failed to find pattern: Bypass Treasure Chest CP Check` and I knew that patch was in Daily Collectibles but just to be sure I started eliminating scripts one by one and trying to go online, my game kept crashing until I disabled Daily Collectibles so I just quoted out both patches. I can play just fine and use the script mainly for Street Dealers so it's not a big deal. If this is not a common issue for everyone else then you can close it if you want.

**Comment by ShinyWasabi** [comment]
Injecting on the landing page should resolve the issue. I will look into this anyway as to why it fails when injected in SP.

**Comment by gir489returns** [comment]
This is due to Lua's Garbage Collection Tag Method being invoked when you switch from SP to MP, Because @ShinyWasabi was declaring them as locals.

@xesdoog Can you please try #31 in tandem with https://github.com/YimMenu/YimMenu/pull/3628?

**Comment by xesdoog** [comment]
> @xesdoog Can you please try #31 in tandem with [YimMenu/YimMenu#3628](https://github.com/YimMenu/YimMenu/pull/3628)?

Of course!

**Comment by gir489returns** [comment]
@ShinyWasabi I told your ass it was the garbage collector. 👌🏻
