### ISSUE TITLE
[ERROR]: YimMenu's New Hash Update [ae64147] makes the Script don't work

### ISSUE THREAD

**Issue by Eedge-e** [YimMenu-Lua/DailyCollectibles#29]
With the recent update, the Daily Collectibles doesn't work.

As it states in the log:

07:02:39.4732479][FATAL/lua_module.cpp:82] ...P\AppData\Roaming\YimMenu\scripts\daily_collectibles.lua:114: attempt to call a nil value (field 'add_patch')
stack traceback:
	...P\AppData\Roaming\YimMenu\scripts\daily_collectibles.lua:114: in main chunk
[07:02:39.4741645][FATAL/lua_module.cpp:329] daily_collectibles.lua failed to load: ...P\AppData\Roaming\YimMenu\scripts\daily_collectibles.lua:114: attempt to call a nil value (field 'add_patch')
stack traceback:
	...P\AppData\Roaming\YimMenu\scripts\daily_collectibles.lua:114: in main chunk

[cout.log](https://github.com/user-attachments/files/16725053/cout.log)

**Comment by ShinyWasabi** [comment]
I am aware of it. I'll update the script soon.

**Comment by ShinyWasabi** [comment]
https://github.com/YimMenu-Lua/DailyCollectibles/commit/8b5bb622a3583ffa9b1820e81d9a70bcb3251e16
